apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-subnet-1
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-1
    availabilityZone: eu-west-1a
    cidrBlock: 192.168.1.0/24
    vpcIdRef:
      name: crossplane-vpc
    tags:
    - key: Name
      value: crossplane-subnet-1
    - key: Owner
      value: Dhouha
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: awsconfig

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-subnet-2
  namespace: crossplane-system  
spec:
  forProvider:
    region: eu-west-1
    availabilityZone: eu-west-1b
    cidrBlock: 192.168.2.0/24
    vpcIdRef:
      name: crossplane-vpc
    tags:
    - key: Name
      value: crossplane-subnet-2
    - key: Owner
      value: Dhouha
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: awsconfig
